# --- IPPO specific parameters ---
action_selector: ~
mask_before_softmax: True

runner: "parallel"

buffer_size: 1000
batch_size: 256

env_args:
  state_last_action: False # critic adds last action internally


lr: 0.001

obs_agent_id: True
obs_last_action: False  # 对的，ppo只有state
obs_individual_obs: False

# use IA2C
agent_output_type: ~
learner: "ppo_learner"
entropy_coef: 0.01
standardise_rewards: True
use_rnn: False
q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "ac_critic"
epochs: 10
eps_clip: 0.2
name: "ippo"