action_range: ~
action_selector: ~
agent: cem
agent_output_type: "q"
batch_size: 100
buffer_size: 1000000
buffer_warmup: 1000
critic_lr: ~
double_q: False
epsilon_decay_mode: ~
epsilon_start: ~
epsilon_finish: ~
epsilon_anneal_time: ~
exploration_mode: "gaussian"
start_steps: 10000 # Number of steps for uniform-random action selection, before running real policy. Helps exploration.
act_noise: 0.1 # Stddev for Gaussian exploration noise added to policy at training time.
ou_theta: 0.15
ou_sigma: 0.2
ou_noise_scale: 0.3
final_ou_noise_scale: 0.
gamma: 0.99
grad_norm_clip: 0.5
learner: "cq_learner"
learn_interval: 1
lr: 0.001
mac: cqmix_mac
mixer: None
naf_hidden_dim: ~
name: "iql-cem"
n_runners: ~
n_train: 1
optimizer: adam
optimizer_epsilon: 0.01
ou_stop_episode: 100 # training noise goes to zero after this episode
run_mode: ~
runner: "parallel"
runner_scope: 'transition'
target_update_interval: ~
target_update_mode: "soft"
target_update_tau: 0.001
test_greedy: ~
verbose: False
weight_decay: True
weight_decay_factor: 0.0001