# --- MAPPO specific parameters ---
action_selector: ~
mask_before_softmax: True

runner: "parallel"

buffer_size: 1000
batch_size: 256

env_args:
  state_last_action: False # critic adds last action internally


lr: 0.001

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

agent_output_type: ~
learner: "ppo_learner"
entropy_coef: 0.01
use_rnn: False
standardise_rewards: True
q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic"
epochs: 10
eps_clip: 0.2
name: "mappo"
